name: Deploy Flask App to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} "echo '✅ Connexion SSH OK'"

      - name: Deploy app
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} "
            # Créer le dossier si besoin
            mkdir -p ~/assimi &&
            cd ~/assimi

            # Récupérer le code
            if [ -d .git ]; then
              git pull origin main
            else
              git clone https://github.com/Aramayac/assimi.git .
            fi

            # Construire et lancer avec Docker Compose
            docker-compose down || true
            docker-compose up -d --build
          "
